<?php return function ($fontDir, $rootDir) {
return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'be vietnam pro' => array(
    '100_italic' => $fontDir . '/be_vietnam_pro_100_italic_834c1b9695ecdc38a6d973dc29ffc341',
    '200_italic' => $fontDir . '/be_vietnam_pro_200_italic_379625b910552b5b214907bb1e251dd6',
    '300_italic' => $fontDir . '/be_vietnam_pro_300_italic_1d2cdeddc665c8d45d68a84b5e70d1e7',
    'italic' => $fontDir . '/be_vietnam_pro_italic_3dc47ccb557ff52b3ea715203eedd524',
    '500_italic' => $fontDir . '/be_vietnam_pro_500_italic_cc4cd2329fab61a19cdd83537a9b53f1',
    '600_italic' => $fontDir . '/be_vietnam_pro_600_italic_bb715a739ba6db51b72fe019f854998e',
    'bold_italic' => $fontDir . '/be_vietnam_pro_bold_italic_c53db4682b504ab8429db68eaebacd88',
    '800_italic' => $fontDir . '/be_vietnam_pro_800_italic_69814cd809032ef566f559b4547a3e9c',
    '900_italic' => $fontDir . '/be_vietnam_pro_900_italic_a635a743ed43f91addcccbc90b55caaf',
    '100' => $fontDir . '/be_vietnam_pro_100_006c7adae3af962d19c2270b6203019d',
    '200' => $fontDir . '/be_vietnam_pro_200_71589957947d3c717092a5a321825b8b',
    '300' => $fontDir . '/be_vietnam_pro_300_c2ef67b135be53aae1b4ef916395d85f',
    'normal' => $fontDir . '/be_vietnam_pro_normal_acb8c5c8cff7d3c91db5eee71b446384',
    '500' => $fontDir . '/be_vietnam_pro_500_e18a787e0d5af1aa49d112a67e35fc88',
    '600' => $fontDir . '/be_vietnam_pro_600_f3ced869d9b56a1b4661b401c9cd9837',
    'bold' => $fontDir . '/be_vietnam_pro_bold_74ebc3ab78b6bba780049cf2a7823cfb',
    '800' => $fontDir . '/be_vietnam_pro_800_95c790c135c6a3593a43bc7131d4f440',
    '900' => $fontDir . '/be_vietnam_pro_900_a044983f9157c20aeb6f853d56245baf',
  ),
);
}; ?>